<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="AQMIT-DSK-10159" ignored="0" name="Default test" tests="1" failures="1" timestamp="20 Apr 2022 07:13:49 GMT" time="122.22" errors="0">
  <testcase name="totalValidation" time="122.174" classname="tests.Ecommerce_tc_4">
    <failure type="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException" message="The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [D:\Users\Temp\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 0.0.0.0] 
Process output: Error: Cannot find module &amp;apos;./wrapAsync&amp;apos;
Require stack:
- D:\Users\Temp\AppData\Roaming\npm\node_modules\appium\node_modules\async\internal\eachOfLimit.js
- D:\Users\Temp\AppData\Roaming\npm\node_modules\appium\node_modules\async\eachOfLimit.js
- D:\Users\Temp\AppData\Roaming\npm\node_modules\appium\node_modules\async\eachOf.js
- D:\Users\Temp\AppData\Roaming\npm\node_modules\appium\node_modules\async\forEach.js
- D:\Users\Temp\AppData\Roaming\npm\node_modules\appium\node_modules\winston\lib\winston\logger.js
- D:\Users\Temp\AppData\Roaming\npm\node_modules\appium\node_modules\winston\lib\winston\create-logger.js
- D:\Users\Temp\AppData\Roaming\npm\node_modules\appium\node_modules\winston\lib\winston.js
- D:\Users\Temp\AppData\Roaming\npm\node_modules\appium\build\lib\logsink.js
- D:\Users\Temp\AppData\Roaming\npm\node_modules\appium\build\lib\main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.&amp;lt;anonymous&amp;gt; (D:\Users\Temp\AppData\Roaming\npm\node_modules\appium\node_modules\async\internal\eachOfLimit.js:19:18)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)

">
      <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [D:\Users\Temp\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 0.0.0.0] 
Process output: Error: Cannot find module './wrapAsync'
Require stack:
- D:\Users\Temp\AppData\Roaming\npm\node_modules\appium\node_modules\async\internal\eachOfLimit.js
- D:\Users\Temp\AppData\Roaming\npm\node_modules\appium\node_modules\async\eachOfLimit.js
- D:\Users\Temp\AppData\Roaming\npm\node_modules\appium\node_modules\async\eachOf.js
- D:\Users\Temp\AppData\Roaming\npm\node_modules\appium\node_modules\async\forEach.js
- D:\Users\Temp\AppData\Roaming\npm\node_modules\appium\node_modules\winston\lib\winston\logger.js
- D:\Users\Temp\AppData\Roaming\npm\node_modules\appium\node_modules\winston\lib\winston\create-logger.js
- D:\Users\Temp\AppData\Roaming\npm\node_modules\appium\node_modules\winston\lib\winston.js
- D:\Users\Temp\AppData\Roaming\npm\node_modules\appium\build\lib\logsink.js
- D:\Users\Temp\AppData\Roaming\npm\node_modules\appium\build\lib\main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\Users\Temp\AppData\Roaming\npm\node_modules\appium\node_modules\async\internal\eachOfLimit.js:19:18)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)


	at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:168)
	at practise.AppiumFramework.base.startServer(base.java:25)
	at tests.Ecommerce_tc_4.totalValidation(Ecommerce_tc_4.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/wd/hub/status] to be available after 120013 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
	at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:133)
	at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:155)
	... 27 more
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:156)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
	... 29 more
]]>
    </failure>
  </testcase> <!-- totalValidation -->
</testsuite> <!-- Default test -->
